### ISSUE TITLE
pkgdown build failing

### ISSUE THREAD

**Issue by maelle** [agricolamz/phonfieldwork#32]
:wave: @agricolamz! I was looking at https://dev.ropensci.org/ and saw the docs building is failing for your package, it'd be nice if it were fixed before your blog post.

https://dev.ropensci.org/blue/organizations/jenkins/phonfieldwork/detail/phonfieldwork/26/pipeline

For context on the docs server https://ropensci.org/technotes/2019/06/07/ropensci-docs/

**Comment by agricolamz** [comment]
Dear @maelle, I guess I fixed it.

https://dev.ropensci.org/blue/organizations/jenkins/phonfieldwork/detail/phonfieldwork/29/pipeline

**Comment by maelle** [comment]
Yay! Could you please use https://docs.ropensci.org/phonfieldwork/ as URL for the package now? 

For info on how to set up a redirect see https://devguide.ropensci.org/redirect.html

**Comment by agricolamz** [comment]
@maelle, I've changed links everywhere, but I'd like to keep gh for a while, since I have some examples that are not rendered into documentation, like [this](https://ropensci.github.io/phonfieldwork/additional/first_example.html) or [this](https://ropensci.github.io/phonfieldwork/additional/stimuli_viewer.html).

**Comment by maelle** [comment]
would there be some ways to incorporate those in a pkgdown website btw? :thinking:

**Comment by agricolamz** [comment]
I don't know. I would be happy not to, because all those examples represent the pure `rmarkdown` result. I'm afraid that `pkgdown` 
will make it fancy and though not representative...
